/** The hidden internals, run the way Orbit runs them on itself: the worker shim and the check runner. */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { makeSandbox, type Sandbox } from './helpers.ts';

const boxes: Sandbox[] = [];
afterEach(() => boxes.splice(0).forEach((b) => b.close()));
const box = () => {
  const b = makeSandbox({ config: null });
  boxes.push(b);
  return b;
};
const json = (path: string) => JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;

describe('orbit shim', () => {
  it('supervises a provider command and records how it ended', async () => {
    const b = box();
    const dir = join(b.base, 'worker');
    mkdirSync(dir, { recursive: true });
    const r = await b.run(['shim', '--worker-dir', dir, '--timeout-ms', '20000', '--', process.execPath, '-e', "console.log(JSON.stringify({type:'ok'})); process.exit(3)"], { detached: true });
    expect(r.code, r.stderr).toBe(0);
    const exit = json(join(dir, 'exit.json'));
    expect(exit).toMatchObject({ version: 1, code: 3, timedOut: false, cancelled: false, error: null });
    expect(readFileSync(join(dir, 'log.jsonl'), 'utf8')).toContain('"type":"ok"');
    expect(json(join(dir, 'pid.json'))).toMatchObject({ version: 1 });
  });

  it('is not part of the public command list but still takes its arguments verbatim', async () => {
    const b = box();
    expect((await b.run(['help'])).stdout).not.toMatch(/\bshim\b/);
    const bad = await b.run(['shim', '--worker-dir', 'relative']);
    expect(bad.code).toBe(2);
    expect(bad.stderr).toMatch(/orbit shim: expected -- followed by the provider command/);
  });
});

describe('orbit check-runner', () => {
  it('runs one check under the check shim and exits with the shim\'s own code', async () => {
    const b = box();
    const runDir = join(b.base, 'run');
    const checkDir = join(runDir, 'checks', 'unit');
    mkdirSync(checkDir, { recursive: true });
    writeFileSync(
      join(checkDir, 'intent.json'),
      JSON.stringify({ token: 'tok-1', checkRunId: 'chk-1', argv: [process.execPath, '-e', "console.log('checked'); process.exit(7)"], cwd: b.repo, timeoutMs: 20_000, killGraceMs: 500, maxOutputBytes: 100_000, writtenAt: Date.now() }),
    );
    const r = await b.run(['check-runner', runDir, checkDir]);
    expect(r.code, r.stderr).toBe(0);
    const exit = json(join(checkDir, 'exit.json'));
    expect(exit).toMatchObject({ token: 'tok-1', exitCode: 7, timedOut: false, error: null });
    expect(readFileSync(join(checkDir, 'output.raw'), 'utf8')).toContain('checked');
    // The shim source was written beside the run, read-only, as the evidence runner does.
    expect(readFileSync(join(runDir, 'check-shim.mjs'), 'utf8')).toMatch(/Generated by Orbit/);
  });

  it('refuses relative paths and the wrong number of arguments', async () => {
    const b = box();
    const r = await b.run(['check-runner', 'run', 'check']);
    expect(r.code).toBe(2);
    expect(r.stderr).toMatch(/usage: orbit check-runner/);
    expect((await b.run(['check-runner'])).code).toBe(2);
  });
});

describe('orbit init as a process', () => {
  it('is idempotent across invocations and never overwrites', async () => {
    const b = makeSandbox({ config: null });
    boxes.push(b);
    const first = await b.run(['init', '--json']);
    expect(first.code, first.stderr).toBe(0);
    expect((JSON.parse(first.stdout) as { config: { status: string } }).config.status).toBe('created');
    const path = join(b.repo, '.orbit', 'config.yaml');
    writeFileSync(path, `${readFileSync(path, 'utf8')}\n# local edit\n`);
    const edited = readFileSync(path, 'utf8');
    const second = await b.run(['init', '--json']);
    const j = JSON.parse(second.stdout) as { config: { status: string }; exclude: { added: string[] } };
    expect(j.config.status).toBe('exists');
    expect(j.exclude.added).toEqual([]);
    expect(readFileSync(path, 'utf8')).toBe(edited);
  });
});
