import { existsSync } from 'node:fs';
import { OrbitError } from '../core/errors.ts';
import { isExecutableFile } from './util.ts';

/**
 * The resident-memory watchdog (`isolation.limits.memory_mb`, gap G24).
 *
 * Memory cannot be a ulimit: RLIMIT_AS breaks runtimes that reserve large
 * virtual ranges (node, the JVM, Go) and macOS ignores RLIMIT_RSS. So the
 * command is started by a small supervisor that stays alive beside it,
 * samples the resident set of every process the command runs (its process
 * group and its descendants, found with `ps`) and, when the sum passes the
 * limit, writes one marker line to stderr, kills all of them with SIGKILL and
 * exits with RESOURCE_LIMIT_EXIT_CODE. The check runner reads that marker and
 * records the failure as a resource-limit failure rather than a plain one.
 *
 * What it does and does not promise (the same text goes into the evidence
 * record through `WrappedCommand.limitations`):
 *   - It samples (every `intervalMs`), so a command that allocates faster than
 *     the interval can overshoot before it is stopped.
 *   - It sums resident sets, so pages shared between processes count once per
 *     process: the limit is conservative, never lax.
 *   - Processes that detach from the command's tree (reparented to init) are
 *     out of its sight.
 *
 * The supervisor is plain CommonJS passed with `node -e`, so it needs no file
 * next to the run and works from a source checkout, a test and the bundle. It
 * imports nothing from Orbit.
 */

/** Exit status of the supervisor when it stopped the command for memory. Distinct from the common 1, 2, 126, 127 and 128+n. */
export const RESOURCE_LIMIT_EXIT_CODE = 198;

/** Starts the one line the supervisor writes to stderr when it enforces the limit. */
export const RESOURCE_LIMIT_MARKER = '[orbit-resource-limit]';

export const DEFAULT_MEMORY_SAMPLE_MS = 500;

/** Consecutive failed samples after which the supervisor stops the command: a limit it cannot check is not enforced. */
const MAX_BLIND_SAMPLES = 5;

export const PS_PATHS: readonly string[] = ['/bin/ps', '/usr/bin/ps'];

export const MEMORY_WATCHDOG_SOURCE = `// Generated by Orbit (isolation/memory.ts). Do not edit.
const { spawn, execFileSync } = require('node:child_process');
const { writeSync } = require('node:fs');
const os = require('node:os');

const psPath = process.argv[1];
const limitMb = Number(process.argv[2]);
const intervalMs = Number(process.argv[3]);
const maxBlind = ${MAX_BLIND_SAMPLES};
const command = process.argv.slice(4);
const MARKER = ${JSON.stringify(RESOURCE_LIMIT_MARKER)};
const EXIT_CODE = ${RESOURCE_LIMIT_EXIT_CODE};

function say(text) {
  try { writeSync(2, text); } catch (e) { /* stderr closed */ }
}

function sample() {
  const out = execFileSync(psPath, ['-axo', 'pid=,ppid=,pgid=,rss='], { encoding: 'utf8', timeout: 5000, maxBuffer: 64 * 1024 * 1024 });
  const rows = [];
  let self = null;
  for (const line of out.split('\\n')) {
    const f = line.trim().split(/\\s+/).map(Number);
    if (f.length < 4 || f.some((n) => !Number.isFinite(n))) continue;
    const row = { pid: f[0], ppid: f[1], pgid: f[2], rssKb: f[3] };
    rows.push(row);
    if (row.pid === process.pid) self = row;
  }
  // The process group counts only when the supervisor leads it; otherwise it is the caller's group and not ours to measure or kill.
  const leads = self !== null && self.pgid === process.pid;
  const byParent = new Map();
  for (const r of rows) {
    if (!byParent.has(r.ppid)) byParent.set(r.ppid, []);
    byParent.get(r.ppid).push(r);
  }
  const members = new Map();
  const stack = [process.pid];
  while (stack.length > 0) {
    for (const r of byParent.get(stack.pop()) || []) {
      if (!members.has(r.pid)) { members.set(r.pid, r); stack.push(r.pid); }
    }
  }
  if (leads) for (const r of rows) if (r.pgid === process.pid && r.pid !== process.pid) members.set(r.pid, r);
  members.delete(process.pid);
  let kb = 0;
  for (const r of members.values()) kb += r.rssKb;
  return { kb, pids: [...members.keys()] };
}

function killAll(pids) {
  for (const pid of pids) {
    try { process.kill(pid, 'SIGKILL'); } catch (e) { /* already gone */ }
  }
}

let child = null;
let blind = 0;
let timer = null;

function enforce(why, pids) {
  if (timer) clearInterval(timer);
  say('\\n' + MARKER + ' ' + why + '; the command was stopped\\n');
  killAll(pids);
  if (child && child.pid !== undefined) { try { child.kill('SIGKILL'); } catch (e) { /* gone */ } }
  process.exit(EXIT_CODE);
}

function check() {
  let s;
  try {
    s = sample();
  } catch (e) {
    blind += 1;
    if (blind >= maxBlind) enforce('memory could not be sampled (' + String(e && e.message ? e.message : e).split('\\n')[0].slice(0, 120) + '), so the limit cannot be enforced', child && child.pid !== undefined ? [child.pid] : []);
    return;
  }
  blind = 0;
  const mb = Math.round(s.kb / 1024);
  if (mb > limitMb) enforce('memory: the command used ' + mb + ' MB resident, over isolation.limits.memory_mb (' + limitMb + ' MB)', s.pids);
}

for (const sig of ['SIGTERM', 'SIGINT', 'SIGHUP']) {
  process.on(sig, () => { if (child) { try { child.kill(sig); } catch (e) { /* gone */ } } });
}

child = spawn(command[0], command.slice(1), { stdio: 'inherit' });
child.on('error', (e) => {
  say('orbit memory watchdog: could not start ' + command[0] + ': ' + String(e && e.message ? e.message : e) + '\\n');
  process.exit(127);
});
child.on('exit', (code, signal) => {
  if (timer) clearInterval(timer);
  process.exit(code !== null ? code : 128 + (os.constants.signals[signal] || 0));
});
timer = setInterval(check, intervalMs);
`;

export function findPs(candidates: readonly string[] = PS_PATHS): string | null {
  return candidates.find((p) => isExecutableFile(p)) ?? null;
}

export interface MemoryWatchdogOptions {
  /** `ps` used to sample; undefined searches the usual locations, null means there is none (tests). */
  ps?: string | null;
  /** node that runs the supervisor; default is the running one. */
  node?: string;
  intervalMs?: number;
}

/**
 * `argv` under the memory watchdog, or unchanged when `memoryMb` is null.
 * Fails closed: a limit that was asked for and cannot be applied is an error,
 * never a silent run without it.
 */
export function withMemoryWatchdog(argv: readonly string[], memoryMb: number | null | undefined, opts: MemoryWatchdogOptions = {}): string[] {
  if (memoryMb === null || memoryMb === undefined) return [...argv];
  if (!Number.isSafeInteger(memoryMb) || memoryMb < 64) throw new OrbitError('CONFIG_INVALID', `isolation.limits.memory_mb must be an integer of at least 64 (got ${String(memoryMb)})`);
  const ps = opts.ps === undefined ? findPs() : opts.ps;
  if (!ps) throw new OrbitError('ISOLATION_UNAVAILABLE', `isolation.limits.memory_mb needs ps to sample memory, and none was found (looked in ${PS_PATHS.join(', ')})`, { rule: 'isolation.limits.memory_mb' });
  const node = opts.node ?? process.execPath;
  if (!existsSync(node)) throw new OrbitError('ISOLATION_UNAVAILABLE', `isolation.limits.memory_mb needs node to run its watchdog, and ${node} does not exist`, { rule: 'isolation.limits.memory_mb' });
  const interval = opts.intervalMs ?? DEFAULT_MEMORY_SAMPLE_MS;
  return [node, '-e', MEMORY_WATCHDOG_SOURCE, ps, String(memoryMb), String(interval), ...argv];
}

/** The marker line a stopped command's output carries, or null. Only a line that starts with the marker counts. */
export function resourceLimitNote(output: string): string | null {
  for (const line of output.split('\n')) {
    if (line.startsWith(RESOURCE_LIMIT_MARKER)) return line.slice(RESOURCE_LIMIT_MARKER.length).trim().slice(0, 300);
  }
  return null;
}
