import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { atomicWrite } from '../core/fsx.ts';
import { sha256 } from '../core/hash.ts';

/**
 * The detached process that owns one check. The controller spawns it and may
 * die; the shim keeps running, enforces the timeout itself, caps the output,
 * and writes `exit.json` atomically when the check ends, so any later
 * controller incarnation can collect the result (docs/architecture.md
 * "Process model").
 *
 * It is plain JavaScript in a string, written next to the run, so it runs
 * identically from a source checkout, a test, and the single-file bundle
 * (which has no separate shim entry for checks). It imports nothing from
 * Orbit: it must stay small enough to audit at a glance.
 *
 * The check runs in its own process group (distinct from the shim's), so the
 * shim can stop the whole tree on timeout or cancellation and still live to
 * report what happened.
 */

export const SHIM_FILES = {
  intent: 'intent.json',
  launch: 'launch.json',
  pid: 'pid.json',
  exit: 'exit.json',
  output: 'output.raw',
} as const;

/** What the controller tells the shim. Environment travels in the shim's own env, never on disk. */
export interface ShimIntent {
  token: string;
  checkRunId: string;
  argv: string[];
  cwd: string;
  timeoutMs: number;
  killGraceMs: number;
  maxOutputBytes: number;
  writtenAt: number;
}

/** Written by the controller right after spawning, to pair the pid with its start time. */
export interface ShimLaunch {
  token: string;
  pid: number;
  procStart: string | null;
}

export interface ShimPid {
  token: string;
  shimPid: number;
  childPid: number | null;
  /** The check's own process group; equals childPid. */
  childPgid: number | null;
  startedAt: number;
}

export interface ShimExit {
  token: string;
  exitCode: number | null;
  signal: string | null;
  timedOut: boolean;
  cancelled: boolean;
  outputBytes: number;
  outputTruncated: boolean;
  endedAt: number;
  /** Set when the check could not be started at all. */
  error: string | null;
}

export const CHECK_SHIM_SOURCE = `// Generated by Orbit (evidence/check-shim.ts). Do not edit.
import { spawn } from 'node:child_process';
import { closeSync, openSync, readFileSync, renameSync, writeFileSync, writeSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
const intent = JSON.parse(readFileSync(join(dir, 'intent.json'), 'utf8'));

function put(name, value) {
  const tmp = join(dir, '.' + name + '.' + process.pid + '.tmp');
  writeFileSync(tmp, JSON.stringify(value));
  renameSync(tmp, join(dir, name));
}

const out = openSync(join(dir, 'output.raw'), 'a', 0o600);
let written = 0;
let dropped = 0;
function sink(chunk) {
  const room = intent.maxOutputBytes - written;
  if (room <= 0) { dropped += chunk.length; return; }
  const part = chunk.length <= room ? chunk : chunk.subarray(0, room);
  writeSync(out, part);
  written += part.length;
  dropped += chunk.length - part.length;
}
function note(text) {
  const b = Buffer.from(text);
  writeSync(out, b);
  written += b.length;
}

let timedOut = false;
let cancelled = false;
let stopping = false;
let finished = false;
let child = null;
let result = { exitCode: null, signal: null, error: null };
let killTimer = null;

function signalGroup(sig) {
  if (!child || child.pid === undefined) return;
  try { process.kill(-child.pid, sig); } catch (e) { /* group already gone */ }
}

function stop() {
  if (stopping) return;
  stopping = true;
  signalGroup('SIGTERM');
  killTimer = setTimeout(() => signalGroup('SIGKILL'), intent.killGraceMs);
}

function finish() {
  if (finished) return;
  finished = true;
  if (killTimer) clearTimeout(killTimer);
  clearTimeout(deadline);
  if (dropped > 0) note('\\n[orbit: output truncated: ' + dropped + ' bytes dropped after the first ' + intent.maxOutputBytes + ']\\n');
  closeSync(out);
  put('exit.json', {
    token: intent.token,
    exitCode: result.exitCode,
    signal: result.signal,
    timedOut,
    cancelled,
    outputBytes: written,
    outputTruncated: dropped > 0,
    endedAt: Date.now(),
    error: result.error,
  });
  process.exit(0);
}

const deadline = setTimeout(() => {
  timedOut = true;
  note('\\n[orbit: check timed out after ' + Math.round(intent.timeoutMs / 1000) + 's and was stopped]\\n');
  stop();
}, intent.timeoutMs);

for (const sig of ['SIGTERM', 'SIGINT', 'SIGHUP']) {
  process.on(sig, () => {
    if (!stopping) cancelled = true;
    note('\\n[orbit: check cancelled]\\n');
    stop();
  });
}

try {
  child = spawn(intent.argv[0], intent.argv.slice(1), {
    cwd: intent.cwd,
    env: process.env,
    detached: true,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
} catch (e) {
  result.error = String(e && e.message ? e.message : e);
  put('pid.json', { token: intent.token, shimPid: process.pid, childPid: null, childPgid: null, startedAt: Date.now() });
  finish();
}

if (child) {
  child.on('error', (e) => {
    result.error = String(e && e.message ? e.message : e);
    finish();
  });
  child.stdout.on('data', sink);
  child.stderr.on('data', sink);
  if (child.pid !== undefined) {
    put('pid.json', { token: intent.token, shimPid: process.pid, childPid: child.pid, childPgid: child.pid, startedAt: Date.now() });
  }
  child.on('exit', (code, signal) => {
    result.exitCode = code;
    result.signal = signal;
    // Whatever the check left running in its group (daemons, watchers) must not outlive it.
    signalGroup('SIGKILL');
    // Output may still be in flight; give the pipes a moment, but never wait for a grandchild that kept them open.
    setTimeout(finish, 300).unref();
    child.on('close', finish);
  });
}
`;

export const CHECK_SHIM_HASH = sha256(CHECK_SHIM_SOURCE);

/** Write the shim into the run directory if it is missing or different. Returns its path. */
export function ensureShim(runDir: string): string {
  const path = join(runDir, 'check-shim.mjs');
  let current: string | null = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* not written yet */
  }
  if (current !== CHECK_SHIM_SOURCE) atomicWrite(path, CHECK_SHIM_SOURCE, 0o444);
  return path;
}

export function readJsonFile<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as T;
  } catch {
    // A torn read cannot happen (writes are renames), so unreadable JSON means a damaged file: treat as absent.
    return null;
  }
}

export function shimPath(dir: string, file: keyof typeof SHIM_FILES): string {
  return join(dir, SHIM_FILES[file]);
}
